package com.cryo.builders;

import ch.simschla.minify.adapter.Minifier;
import com.cryo.DBConnection;
import com.cryo.NewWorldWikiBuilder;
import com.cryo.WikiBuilder;
import com.cryo.entities.*;
import com.cryo.utils.Utils;
import com.google.gson.internal.LinkedTreeMap;
import de.neuland.pug4j.Pug4J;
import org.apache.commons.codec.digest.DigestUtils;
import org.apache.commons.io.output.ByteArrayOutputStream;
import org.apache.commons.lang3.ArrayUtils;
import org.postgresql.util.PGobject;

import java.io.*;
import java.util.*;

public class ItemDefinitionsBuilder extends Builder {

	private static final String ITEM_DEFINITIONS_PATH = "D:/workspace/github/NewWorldUnpacker/decompiled/sharedassets/springboardentitites/datatables/";
	public static final String ITEM_ICONS_PATH = "D:/workspace/github/NewWorldUnpacker/decompiled/lyshineui/images/icons/items";

	private static HashMap<String, ItemDefinitions> itemDefinitions;
	private static HashMap<String, ItemDefinitions> itemDefinitionsById;

	private static String CSS;

	private static String MINIFIED_CSS;

	@Override
	public void build() {

		DBConnection connection = NewWorldWikiBuilder.getConnection();

		connection.delete("pages", "path LIKE ?", "items/%");

		record NameId(String name, String id) {}

		List<NameId> toRemove = new ArrayList<>();
		for(ItemDefinitions defs : itemDefinitions.values()) {
			if(defs.getName().contains("Crafted"))
				toRemove.add(new NameId(defs.getName().replace("Crafted", ""), defs.getItemID()));
		}

		for(NameId remove : toRemove) {
			itemDefinitions.remove(remove.name);
			itemDefinitionsById.remove(remove.id);
		}

		try {
			for (ItemDefinitions defs : itemDefinitions.values()) {

				String name = defs.getName().replace("@", "");
				if (name.equals("")) continue;
				if (!WikiBuilder.localizationStrings.containsKey(name)) continue;
				name = WikiBuilder.localizationStrings.get(name);
				final String displayName = name;

				if(!displayName.equalsIgnoreCase("Protective Wyrd Shoes")) continue;

				String description = defs.getDescription().replace("@", "");
				description = WikiBuilder.localizationStrings.getOrDefault(description, "");

				String itemTypeName = defs.getItemTypeDisplayName().replace("@", "");
				itemTypeName = WikiBuilder.localizationStrings.getOrDefault(itemTypeName, defs.getItemType());

				HashMap<String, Object> model = new HashMap<>();

				model.put("item", defs);

				String path = "items/" + itemTypeName.toLowerCase().replace(" ", "-") + "/" + displayName.replace(" ", "_").replace(":", "");

				ArrayList<Properties> props = new ArrayList<>();

				Properties nameProp = new Properties();
				nameProp.put("title", displayName);
				nameProp.put("anchor", "#" + displayName.toLowerCase().replace(" ", "-"));
				nameProp.put("children", new ArrayList<Properties>());
				props.add(nameProp);

				List<Recipe> obtained = defs.getObtainedFrom();
				List<Recipe> usedIn = defs.getUsedIn();
				if(obtained != null && obtained.size() > 0) {
					Properties dropSources = new Properties();
					dropSources.put("title", "Sources");
					dropSources.put("anchor", "#sources");
					dropSources.put("children", new ArrayList<Properties>());
					props.add(dropSources);

					model.put("obtained", obtained);
				}
				if(usedIn != null && usedIn.size() > 0) {
					Properties craftingRecipes = new Properties();
					craftingRecipes.put("title", "Crafting Recipes");
					craftingRecipes.put("anchor", "#crafting-recipes");
					craftingRecipes.put("children", new ArrayList<Properties>());
					props.add(craftingRecipes);

					model.put("usedIn", usedIn);
				}

				File imageFile = new File(ITEM_ICONS_PATH + "/" + defs.getItemType().toLowerCase() + "/" + defs.getIconPath().toLowerCase() + ".png");
				if (!imageFile.exists()) {
					System.err.println("Cannot find icon for " + displayName + ". IconPath: " + defs.getIconPath() + " Path: " + imageFile.getPath());
					continue;
				}

				String html;
				try {
					html = Pug4J.render("data/templates/items/template.pug", model);
				} catch(Exception e) {
					e.printStackTrace();
					continue;
				}

				String entriesJSON = NewWorldWikiBuilder.getGson().toJson(props);

				PGobject toc = new PGobject();
				toc.setType("json");
				toc.setValue(entriesJSON);

				PGobject json = new PGobject();
				json.setType("json");
				json.setValue("{\"js\":\"\",\"css\":\""+MINIFIED_CSS+"\"}");

				connection.delete("pages", "path=?", path);

				Page pageDAO = new Page(-1, path, "hash", displayName, description, false, true, null, "", "", html, html, toc, "html", "", "", "code", "en", 5, 5, json);

				int pageId = connection.insert("pages", pageDAO);

				if (pageId == -1) return;
				PageTag itemTag = new PageTag(-1, pageId, 3);
				PageTag autoGeneratedTag = new PageTag(-1, pageId, 4);

				Tag tag = connection.selectClass("tags", "tag=?", Tag.class, itemTypeName.toLowerCase().replace(" ", "-"));
				int tagId;
				if (tag == null) {
					tag = new Tag(-1, itemTypeName.toLowerCase().replace(" ", "-"), itemTypeName.toLowerCase().replace(" ", "-"), Utils.getTimestamp(), Utils.getTimestamp());
					tagId = connection.insert("tags", tag);
				} else tagId = tag.getId();

				PageTag itemTypeTag = new PageTag(-1, pageId, tagId);

				connection.insert("pageTags", itemTag);
				connection.insert("pageTags", autoGeneratedTag);
				connection.insert("pageTags", itemTypeTag);

				System.out.println("Built: "+displayName+" Link: http://new-world.wiki/en/"+path);
//				return;
			}

		} catch (Exception e) {
			e.printStackTrace();
			return;
		}
	}

	public static HashMap<String, ItemDefinitions> getItemDefinitions() {
		return itemDefinitions;
	}

	public static HashMap<String, ItemDefinitions> getItemDefinitionsById() {
		return itemDefinitionsById;
	}

	public static void loadCSSTemplate() {
		File file = new File("data/templates/items/style.css");

		try {
			BufferedReader reader = new BufferedReader(new FileReader(file));
			StringBuilder builder = new StringBuilder();
			String line;
			while((line = reader.readLine()) != null) builder.append(line);
			reader.close();

			CSS = builder.toString();

			Minifier minifier = Minifier.CSS;
			ByteArrayOutputStream out = new ByteArrayOutputStream();

			InputStream in = new ByteArrayInputStream(CSS.getBytes());
			minifier.minify(in, out, null, null);

			in.close();
			MINIFIED_CSS = new String(out.toByteArray());

		} catch(Exception e) {
			e.printStackTrace();
		}
	}

	public static void loadItemDefinitions() {

		File[] files = new File(ITEM_DEFINITIONS_PATH).listFiles();
		if (files == null) return;

		itemDefinitions = new HashMap<>();
		itemDefinitionsById = new HashMap<>();
		for (File file : files) {
			try {
				if (!file.getName().contains("itemdefinitions_master")) continue;

				BufferedReader reader = new BufferedReader(new FileReader(file));
				StringBuilder builder = new StringBuilder();
				String line;
				while ((line = reader.readLine()) != null) builder.append(line);
				reader.close();

				List<LinkedTreeMap<String, Object>> list = NewWorldWikiBuilder.getGson().fromJson(builder.toString(), ArrayList.class);

				for (LinkedTreeMap<String, Object> map : list) {

					ItemDefinitions defs = new ItemDefinitions(map);
					itemDefinitions.put(defs.getName(), defs);
					itemDefinitionsById.put(defs.getItemID(), defs);
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
}
